"""Remove away status

Revision ID: 0babd60d697b
Revises: d6f7427657fb
Create Date: 2024-06-24 00:06:31.678539

"""
from alembic import op
import sqlalchemy as sa

import Database

# revision identifiers, used by Alembic.
revision = '0babd60d697b'
down_revision = 'd6f7427657fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.drop_column('away')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('away', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
